### ISSUE TITLE
JDBC: pgbouncer admin database login fails: sends wrong client encoding to driver. String-replace "UNICODE" by "UTF8" works

### ISSUE THREAD

**Issue by cfr-rec** [pgbouncer/pgbouncer#165]
Hi,

I tried to connect to the pgbouncer administration database "pgbouncer" by means of a java client (using the postgresql JDBC driver v 9.4.1211-jdbc42 with Java 1.8).

However, the connections fails with "Protocol error.  Session setup failed.". I have already traced down the problem to a large degree: the postgres JDBC driver expects a client encoding of "UTF8" (hard-coded), but pgbouncer sends "UNICODE". Interestingly, this only happens for the "pgbouncer" database -- all other databases work fine.

I wrote a small TCP proxy which replaces "UNICODE" by "UTF8" in the TCP stream -- and the java client is able to connect and to execute "SHOW POOLS" etc.

Here is a minimal working example which reproduces the problem:

```java
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.LinkedHashMap;
import java.util.Map;

import org.postgresql.ds.PGSimpleDataSource;
import org.postgresql.jdbc.PreferQueryMode;

public class MainCfr
{
  public static void main(String[] args) throws Exception
  {
    Class.forName("org.postgresql.Driver");

    final String user = "postgres";
    final String password = "XXX";

    DriverManager.setLogStream(System.out);

    PGSimpleDataSource ds = new PGSimpleDataSource();
    ds.setDatabaseName("pgbouncer");
    ds.setPassword(password);
    ds.setUser(user);
    ds.setPortNumber(6543);
    ds.setServerName("localhost");
    ds.setLoglevel(10);

    // this is _mandatory_ for pgbouncer and _requires_ a decent JDBC driver version:
    ds.setPreferQueryMode(PreferQueryMode.SIMPLE);

    try (Connection conn = ds.getConnection())
    {
      try (Statement statement = conn.createStatement())
      {
        try (ResultSet res = statement.executeQuery("SHOW POOLS"))
        {
          ResultSetMetaData metaData = res.getMetaData();
          while (res.next())
          {
            Map<String, Object> values = new LinkedHashMap<>();
            for (int i = 0; i < metaData.getColumnCount(); ++i)
            {
              String columnName = metaData.getColumnName(i + 1);
              values.put(columnName, res.getObject(i + 1));
            }

            System.out.println(values);
          }
        }

      }
    }
    System.out.println("done");

    System.exit(0);
  }

}
```

It produces the following output:

```
DriverManager.getConnection("jdbc:postgresql://localhost:6543/pgbouncer?loglevel=10&preferQueryMode=simple")
    trying org.apache.derby.jdbc.AutoloadedDriver
    trying org.apache.derby.jdbc.ClientDriver
    trying oracle.jdbc.OracleDriver
    trying com.mysql.jdbc.Driver
    trying com.mysql.fabric.jdbc.FabricMySQLDriver
    trying org.postgresql.Driver
13:57:53.184 (1) PostgreSQL 9.4.1211
13:57:53.196 (1) Trying to establish a protocol version 3 connection to localhost:6543
13:57:53.208 (1) Receive Buffer Size is 65536
13:57:53.208 (1) Send Buffer Size is 65536
13:57:53.211 (1)  FE=> StartupPacket(user=postgres, database=pgbouncer, client_encoding=UTF8, DateStyle=ISO, TimeZone=Europe/Berlin, extra_float_digits=2)
13:57:53.211 (1)  <=BE AuthenticationReqMD5(salt=1fb082e9)
13:57:53.217 (1)  FE=> Password(md5digest=md5b28cf959f84ee684d9c80f27aae49767)
13:57:53.217 (1)  <=BE AuthenticationOk
13:57:53.244 (1)  <=BE ParameterStatus(server_version = 1.7.1/bouncer)
13:57:53.244 (1)  <=BE ParameterStatus(client_encoding = UNICODE)
org.postgresql.util.PSQLException: Protocol error.  Session setup failed.
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2612)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:116)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:225)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:55)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:219)
	at org.postgresql.Driver.makeConnection(Driver.java:407)
	at org.postgresql.Driver.connect(Driver.java:275)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:89)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:74)
	at integration.recommind.axc.jobs55.MainCfr.main(MainCfr.java:80)
SQLException: SQLState(08P01)
getConnection failed: org.postgresql.util.PSQLException: Protocol error.  Session setup failed.
Exception in thread "main" org.postgresql.util.PSQLException: Protocol error.  Session setup failed.
	at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2612)
	at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:116)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:225)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:55)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:219)
	at org.postgresql.Driver.makeConnection(Driver.java:407)
	at org.postgresql.Driver.connect(Driver.java:275)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:89)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:74)
	at integration.recommind.axc.jobs55.MainCfr.main(MainCfr.java:80)
```

I am using 
* pgbouncer 1.7.2 (which reports the wrong version number 1.7.1 as you may know already).
* win32 version downloaded from http://winpg.jp/~saito/pgbouncer/pgbouncer-1.7.2-win32.zip
* Java 1.8
* postgresql JDBC driver v 9.4.1211-jdbc42 

I know that the issue was present in pgbouncer 1.6.1 as well. I can confirm that substituting "UNICODE" by "UTF8" during the session setup works well (as mentioned above).

I would appreciate it if you could modify access to the admin database such that it respects the correct client_encoding. this would allow me to use a java client without any dirty hacks or without the need to resort to a system call.

**Comment by cfr-rec** [comment]
pgbouncer.ini is

```
[databases]
ngdb = host=localhost port=5432 pool_size=250


[pgbouncer]
listen_port = 6543
listen_addr = *
auth_type = md5
auth_file = C:\ws\default\mindserver-projects\pgbouncer.6543\users.txt

; apparently, pgbouncer cannot roll its log :-(
logfile =   C:\ws\default\mindserver-projects\pgbouncer.6543/pgbouncer.log
; deactivate pidfile: it causes only harm
; pidfile = C:\ws\default\mindserver-projects\pgbouncer.6543/pgbouncer.pid
admin_users = postgres

; more is unsupported by our target postgres revisions (and maybe by our usage patterns)
pool_mode = session

; max client connections
max_client_conn = 10000

; Period for writing aggregated stats into log.
; You can increase this if the log becomes too large
; stats_period = 60
; log_connections = 0
; log_disconnections = 0

; configures the default 'pool_size' for each entry in [databases]:
default_pool_size = 200

reserve_pool_size = 0
reserve_pool_timeout = 5

; If a server connection has been idle more than this many seconds it will be dropped. If 0 then timeout is disabled. [seconds]
server_idle_timeout = 600

; ignores extra jdbc parameters in pgbouncer. prevents engine from start if not set.
ignore_startup_parameters = extra_float_digits
```

users.ini is standard

**Comment by markokr** [comment]
Yeah, seems like UTF8 is the proper encoding name.

Fixed in master.
