### ISSUE TITLE
Could not drop database from pgbouncer

### ISSUE THREAD

**Issue by zw963** [pgbouncer/pgbouncer#189]
I use ruby on rails 5.0.2 ActiveRecord, it connection to pgbouncer,
which then connect to another postgresql instance.

current problem is:

1. if Rails connect to my postgresql instance, all is worked.
2.  Rails connect to  pgbouncer, migration and CRUD is worked.
     But, could not drop database or create database.

Following is error messages:

```sh
╰─ $ rake db:drop
Running via Spring preloader in process 20696
ERROR:  No such database: postgres
Couldn't drop database 'ershou_web_development'
rake aborted!
PG::ConnectionBad: ERROR:  No such database: postgres
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `initialize'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `new'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `connect'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:91:in `connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/tasks/postgresql_database_tasks.rb:6:in `connection'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/tasks/postgresql_database_tasks.rb:28:in `drop'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:136:in `drop'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:152:in `block in drop_current'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:292:in `block in each_current_configuration'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:291:in `each'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:291:in `each_current_configuration'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:151:in `drop_current'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:42:in `block (2 levels) in <top (required)>'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:38:in `block (2 levels) in <top (required)>'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/zw963/.rvm/gems/ruby-2.3.3@ershou_web/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
-e:1:in `<main>'
Tasks: TOP => db:drop:_unsafe
(See full trace by running task with --trace)
```

Thanks

**Comment by zw963** [comment]
Following is create db error message:

```cl
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "username"=>"postgres", "password"=>123456, "host"=>"127.0.0.1", "port"=>5433, "database"=>"ershou_web_development"}
rake aborted!
PG::ConnectionBad: ERROR:  No such database: postgres
```

**Comment by zw963** [comment]
my pgbouncer config:

```sh
[databases]
ershou_web_development = host=ershou-web.pg-master.5432 dbname=ershou_web_development port=5432 user=postgres

[pgbouncer]
user = pgbouncer
pool_mode = session
server_reset_query = DISCARD ALL
listen_port = 5432
listen_addr = 0.0.0.0
auth_type = any
query_wait_timeout= 60
```

**Comment by eulerto** [comment]
@zw963 It seems you forgot to add a postgres entry in databases section because your application is complaining about it (No such database: postgres).

[databases]
ershou_web_development = host=ershou-web.pg-master.5432 dbname=ershou_web_development port=5432 user=postgres
postgres = host=ershou-web.pg-master.5432 dbname=postgres port=5432 user=postgres

**Comment by zw963** [comment]
Yes. Thanks very much!

**Comment by zw963** [comment]
@eulerto , Hi, seem like still not fullly fix my issue ... : (

Though, I almost don't think this is some issue about pgbouncer, anyway, 
reply here for discuss.

When I add pgbouncer `postgres` config in, previous issue is gone, But, 
ActiveRecord (Ruby on rails ORM) detect one session is using this database,
and refuse to drop it.
```sh
PG::ObjectInUse: ERROR:  database "niuniuway_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
: DROP DATABASE IF EXISTS "niuniuway_development"
Couldn't drop database 'niuniuway_development'
rake aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  database "niuniuway_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
: DROP DATABASE IF EXISTS "niuniuway_development"
```

But, i can force drop it with connect to databse with `psql` directly ...


```sh
╰─ $ 2  /usr/local/pgsql/bin/psql -h 127.0.0.1 -p 6432 -U postgres
psql (9.6.0, server 9.5.5)
Type "help" for help.

postgres=# DROP DATABASE IF EXISTS "niuniuway_development";
ERROR:  database "niuniuway_development" is being accessed by other users
DETAIL:  There is 1 other session using the database.
postgres=# DROP DATABASE IF EXISTS "niuniuway_development";
DROP DATABASE
```

**Comment by zw963** [comment]
Oh, I can create db with:

```sh
 ╰─ $ command rake db:create
Created database 'niuniuway_development'
Database 'niuniuway_test' already exists
```

So, I think this issue is not about pgbouncer ? 
Thanks

**Comment by eulerto** [comment]
@zw963 Don't use a pooler (pgbouncer) to drop a database used as a pool. If the pool is not used, the DROP will succeed, however, if the pool is in use or was recently used, there will be open connection(s) to that database (hence, you won't be able to drop it).
FYI, there is a KILL command to drop client and server connections to a specific database immediately. You should use it **before** dropping a database via pgbouncer. 'KILL mydb' should be executed in 'pgbouncer' virtual database.

**Comment by zw963** [comment]
@eulerto , Nice to know that, thanks very much!!

**Comment by zw963** [comment]
@eulerto , until now, I just test `KILL` command, it worked, dababase is dropped.

I could create and migration database as usual with postgres default port, all worked

but , when i want to connect postgres with pgbouncer port again, it not worked.

it not reconnect to database when I try to access,got following error:

```
PG::ConnectionBad: ERROR:  pgbouncer cannot connect to server
```

Thanks

**Comment by zw963** [comment]
@eulerto , I try to ``psql -p 6432 pgbouncer -c 'RELOAD'``, it not work.

I have to run `pgbouncer -R /config/pgbouncer.ini -d` to make it work again.

the key is: If i need restart pgbouncer, I can just kill pgbouncer for drop db success.

so, I think I do the the thing wrong way.

the problem is: after I `KILL mydb`, what to do make pgboncer worked again?

**Comment by dannyadair** [comment]
`RESUME mydb`

"KILL db
Immediately drop all client and server connections on given database.

New client connections to a killed database will wait until RESUME is called."

...

RESUME [db]
Resume work from previous KILL, PAUSE, or SUSPEND command."

https://www.pgbouncer.org/usage.html
