### ISSUE TITLE
Run db migrate failed with pgbouncer.

### ISSUE THREAD

**Issue by zw963** [pgbouncer/pgbouncer#201]
I use ruby on rails + pg to development web app.
I switch to pgbouncer with a `pg+pgbouncer` container.

I seem like worked well, until today, I add some migrate, if failed.

following is failed message: 

```sh
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:671: warning: Failed to set the default_internal encoding to UTF8: 'server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
'
rake aborted!
ActiveRecord::StatementInvalid: PG::ConnectionBad: PQsocket() can't get socket descriptor: SET client_min_messages TO 'warning'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:332:in `client_min_messages='
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:687:in `configure_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `connect'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:91:in `connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1100:in `initialize'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `new'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/bin/bundle:22:in `load'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/bin/bundle:22:in `<main>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `eval'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `<main>'
PG::ConnectionBad: PQsocket() can't get socket descriptor
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `async_exec'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:98:in `block in execute'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:97:in `execute'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:332:in `client_min_messages='
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:687:in `configure_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `connect'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:217:in `initialize'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `new'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:729:in `new_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:773:in `checkout_new_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:752:in `try_to_checkout_new_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:713:in `acquire_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:490:in `checkout'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:364:in `connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:883:in `retrieve_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:128:in `retrieve_connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_handling.rb:91:in `connection'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1100:in `initialize'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `new'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:1006:in `up'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/migration.rb:984:in `migrate'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/tasks/database_tasks.rb:161:in `migrate'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/bin/bundle:22:in `load'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/bin/bundle:22:in `<main>'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `eval'
/mnt/data_disk_1/www/ershou_web/ershou_web_production/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

In this docker container, I exposed two port (5432 is pg, 6442 is pgbouncer),
so i have to switch to 5432, it worked now.

Following is my pgbouncer config, `pgbouncer.ini`
```sh
[databases]
* = host=127.0.0.1 port=5432 user=postgres

[pgbouncer]
user = postgres

pool_mode = session
server_reset_query = DISCARD ALL

listen_addr = *
listen_port = 6432
unix_socket_dir = /var/run/postgresql

logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid

# default type is md5, but can accept plain.
# auth_type = any
auth_file = /config/users.txt
```

Following is ``users.text``

```sh
"postgres" "123456"
```

```sh
root@01efdefe4a32:/# pgbouncer -V
pgbouncer version 1.7.2
```

**Comment by zw963** [comment]
ping @eulerto, Could you please help me a little ? 

Thanks

**Comment by zw963** [comment]
Any one could help? Thanks.

**Comment by zw963** [comment]
I have test in another machine, it seem like worked.

Thanks
