### ISSUE TITLE
Pgbouncer 1.6 segfaults if we try to connect to pgbouncer DB using admin user and connection logging is on

### ISSUE THREAD

**Issue by artms** [pgbouncer/pgbouncer#67]
Steps to reproduce:
Debian Jessie (I think it is affecting all distributions)
1. Use this config (really only log_connections=1 matters)
```
[databases]
[pgbouncer]
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
unix_socket_dir = /var/run/postgresql
auth_type = any
admin_users = root,postgres
stats_users = nagios
pool_mode = transaction
server_reset_query =
ignore_startup_parameters = extra_float_digits
server_check_query =
server_check_delay = 300
listen_port = 6432
listen_addr = 0.0.0.0
max_client_conn = 2048
default_pool_size = 224
reserve_pool_size = 0
min_pool_size = 32
idle_pool_goal = 32
query_wait_timeout = 10
application_name_add_host = 1
log_connections = 0
log_disconnections = 1
log_pooler_errors = 1
server_lifetime = 300
server_idle_timeout = 240
```
2. Start pgbouncer:
```
/usr/sbin/pgbouncer /etc/pgbouncer/pgbouncer.ini
```
3. On another console execute:
```
psql -p 6432 pgbouncer -U postgres
or
psql -p 6432 pgbouncer -U root
```
4. Pgbouncer crashes

Stacktrace:
```
Core was generated by `/usr/sbin/pgbouncer /etc/pgbouncer/pgbouncer.ini'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fb64b289e2c in _IO_vfprintf_internal (s=s@entry=0x7ffe2b9ca230, format=<optimized out>, format@entry=0x41d9a8 "login attempt: db=%s user=%s", ap=ap@entry=0x7ffe2b9ca3a8) at vfprintf.c:1642
1642	vfprintf.c: No such file or directory.
(gdb) bt
#0  0x00007fb64b289e2c in _IO_vfprintf_internal (s=s@entry=0x7ffe2b9ca230, format=<optimized out>, format@entry=0x41d9a8 "login attempt: db=%s user=%s", ap=ap@entry=0x7ffe2b9ca3a8) at vfprintf.c:1642
#1  0x00007fb64b2b1459 in _IO_vsnprintf (string=0x7ffe2b9ca530 "login attempt: db=pgbouncer user=\246\234+\376\177", maxlen=<optimized out>, format=format@entry=0x41d9a8 "login attempt: db=%s user=%s", 
    args=args@entry=0x7ffe2b9ca3a8) at vsnprintf.c:119
#2  0x00000000004173a9 in log_generic (level=level@entry=LG_INFO, ctx=ctx@entry=0xcd27d0, fmt=fmt@entry=0x41d9a8 "login attempt: db=%s user=%s") at lib/usual/logging.c:168
#3  0x00000000004067a7 in finish_set_pool (client=0xcd27d0, takeover=<optimized out>) at src/client.c:145
#4  0x0000000000406f3d in decide_startup_pool (pkt=<optimized out>, client=<optimized out>) at src/client.c:405
#5  handle_client_startup (client=client@entry=0xcd27d0, pkt=pkt@entry=0x7ffe2b9cb6d0) at src/client.c:457
#6  0x00000000004077a5 in client_proto (sbuf=0xcd2888, evtype=<optimized out>, data=0x7ffe2b9cb720) at src/client.c:620
#7  0x0000000000410a2e in sbuf_call_proto (sbuf=sbuf@entry=0xcd2888, event=event@entry=0) at src/sbuf.c:328
#8  0x0000000000410dfa in sbuf_process_pending (sbuf=0xcd2888) at src/sbuf.c:480
#9  0x0000000000411008 in sbuf_main_loop (sbuf=0xcd2888, skip_recv=<optimized out>) at src/sbuf.c:652
#10 0x00007fb64b82f3dc in event_base_loop () from /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5
#11 0x000000000040a783 in main_loop_once () at src/main.c:642
#12 0x0000000000402d89 in main (argc=4317506, argv=0x7fb64b857e35) at src/main.c:799
```
```
client->auth_user is NULL
```

I can provide core dump if required. It is only affecting users in `admin_users` list

**Comment by markokr** [comment]
Please test if this fixes your problem.

**Comment by artms** [comment]
Yes, it fixed the issue, not more segfaults:
```
2015-08-31 18:05:03.546 101819 LOG C-0x1bd9938: pgbouncer/pgbouncer@unix(108473):6432 login attempt: db=pgbouncer user=pgbouncer
```
